language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - rbx-2
  - jruby-19mode
install:
  - gem install multi_json
  - gem install cutest -v 1.1.3
  - gem install codeclimate-test-reporter
script:
  RUBYLIB=./lib cutest test/*_test.rb
