language: ruby
rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - 2.0.0
  - jruby-head
install:
  - gem install multi_json
  - gem install cutest -v 1.1.3
  - gem install codeclimate-test-reporter
script:
  RUBYLIB=./lib cutest test/*_test.rb
